# docker-compose.yaml
version: '3'

services:
  postgres:
    restart: always
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testing
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
     - "5433:5433"
  web:
    build: .
    command: flask run
    volumes:
      - type: bind
        source: .
        target: /code
    environment:
      - ENV FLASK_APP=app.py
        ENV FLASK_RUN_HOST=0.0.0.0
    ports:
      - target: 5050
        published: 5050